import {expect} from 'chai';
import {ethers} from 'hardhat';
import {time} from '@nomicfoundation/hardhat-network-helpers';
describe('XStocks share custody',()=>{
 async function fixture(amount=2220000000000000n){
 const [buyer,seller,arbiter,outsider]=await ethers.getSigners();const token:any=await ethers.deployContract('MockRebasingStock'),hash=ethers.id('share terms'),evidence=ethers.id('evidence');
 const terms={offerId:ethers.id('offer'),termsHash:hash,buyer:buyer.address,seller:seller.address,arbiter:arbiter.address,token:await token.getAddress(),amount,fundBy:await time.latest()+86400,dispatchWindow:86400,deliveryWindow:86400,inspectionWindow:172800};
 const escrow:any=await ethers.deployContract('XStocksTradeEscrow',[terms]),address=await escrow.getAddress();await token.mintShares(buyer.address,amount*10n);await token.approve(address,amount);await escrow.connect(seller).acceptTerms(hash);
 const fund=()=>escrow.fund(hash),dispatch=async()=>{await fund();await escrow.connect(seller).markDispatched(evidence)};return {buyer,seller,arbiter,outsider,token,hash,evidence,terms,escrow,address,fund,dispatch};}
 it('reproduces NVDA rounding yet funds exact shares only once',async()=>{const c=await fixture();await c.fund();expect(await c.escrow.fundedShares()).eq(2216229757026900n);expect(await c.token.balanceOf(c.address)).eq(c.terms.amount-1n);expect(await c.token.allowance(c.buyer.address,c.address)).eq(0n);await expect(c.fund()).revertedWithCustomError(c.escrow,'InvalidState');});
 for(const m of [900000000000000000n,1200000000000000000n])for(const refund of [true,false])it(`settles all shares: multiplier ${m}, refund ${refund}`,async()=>{const c=await fixture();await c.dispatch();const q=await c.escrow.fundedShares(),before=await c.token.sharesOf(c.buyer.address);await c.token.setMultiplier(m);if(refund){await c.escrow.connect(c.seller).refundBySeller(c.evidence);expect(await c.token.sharesOf(c.buyer.address)-before).eq(q);}else {await c.escrow.approveRelease();expect(await c.token.sharesOf(c.seller.address)).eq(q);}expect(await c.token.sharesOf(c.address)).eq(0n);});
 it('conserves uneven disputed split shares after negative rebase',async()=>{const c=await fixture();await c.dispatch();await c.escrow.openDispute(c.evidence);const q=await c.escrow.fundedShares(),before=await c.token.sharesOf(c.buyer.address),part=c.terms.amount/3n;await c.token.setMultiplier(900000000000000000n);await c.escrow.connect(c.arbiter).resolveDispute(part,c.evidence);expect(await c.token.sharesOf(c.buyer.address)-before).eq(q*part/c.terms.amount);expect(await c.token.sharesOf(c.seller.address)).eq(q-q*part/c.terms.amount);expect(await c.token.sharesOf(c.address)).eq(0n);});
 it('isolates donations from principal through positive rebase',async()=>{const c=await fixture();await c.token.mintShares(c.address,7n);await c.fund();const q=await c.escrow.fundedShares();await c.token.mintShares(c.address,9n);await c.token.setMultiplier(2000000000000000000n);await expect(c.escrow.connect(c.outsider).recoverExcess()).revertedWithCustomError(c.escrow,'Unauthorized');await c.escrow.recoverExcess();expect(await c.token.sharesOf(c.address)).eq(q);});
 it('rejects zero shares and short transfer deposits',async()=>{const c=await fixture(1n);await expect(c.fund()).revertedWithCustomError(c.escrow,'IncorrectFunding');const d=await fixture();await d.token.setShortTransfer(true);await expect(d.fund()).revertedWithCustomError(d.escrow,'IncorrectFunding');expect(await d.escrow.state()).eq(1n);});
 it('rolls back short payouts',async()=>{const c=await fixture();await c.dispatch();await c.token.setShortTransfer(true);await expect(c.escrow.approveRelease()).revertedWithCustomError(c.escrow,'ShareTransferMismatch');expect(await c.escrow.state()).eq(3n);expect(await c.token.sharesOf(c.address)).eq(await c.escrow.fundedShares());});
 it('enforces buyer and accepted terms',async()=>{const c=await fixture();await expect(c.escrow.connect(c.seller).fund(c.hash)).revertedWithCustomError(c.escrow,'Unauthorized');await expect(c.escrow.fund(ethers.id('other'))).revertedWithCustomError(c.escrow,'InvalidTerms');});

 it('supports mutual settlement and recovers post-terminal donations',async()=>{const c=await fixture();await c.dispatch();await c.escrow.openDispute(c.evidence);await c.escrow.proposeSettlement(c.terms.amount/2n,c.evidence);await c.escrow.connect(c.seller).acceptSettlement(1n,c.terms.amount/2n,c.evidence);expect(await c.token.sharesOf(c.address)).eq(0n);await c.token.mintShares(c.address,13n);await c.escrow.recoverExcess();expect(await c.token.sharesOf(c.address)).eq(0n);});
 it('refunds after missed dispatch and releases after buyer inspection',async()=>{const c=await fixture();await c.fund();await time.increaseTo(await c.escrow.dispatchBy());await c.escrow.refundUndispatched();expect(await c.token.sharesOf(c.address)).eq(0n);const d=await fixture();await d.dispatch();await d.escrow.confirmReceipt();await time.increaseTo(await d.escrow.inspectUntil());await d.escrow.connect(d.seller).releaseAfterInspection();expect(await d.token.sharesOf(d.address)).eq(0n);});
 it('rolls back first split payout when second recipient fails',async()=>{const c=await fixture();await c.dispatch();await c.escrow.openDispute(c.evidence);const before=await c.token.sharesOf(c.buyer.address),q=await c.escrow.fundedShares();await c.token.setBlocked(c.seller.address);await expect(c.escrow.connect(c.arbiter).resolveDispute(c.terms.amount/2n,c.evidence)).reverted;expect(await c.token.sharesOf(c.buyer.address)).eq(before);expect(await c.token.sharesOf(c.address)).eq(q);expect(await c.escrow.state()).eq(5n);});
 it('factory binds seller, approved asset, authority, and duplicate offer',async()=>{const c=await fixture();const safe:any=await ethers.deployContract('MockUSDC');const factory:any=await ethers.deployContract('XStocksTradeEscrowFactory',[await safe.getAddress(),[await c.token.getAddress()]]);const terms={...c.terms,arbiter:await safe.getAddress()};await expect(factory.create(terms)).revertedWithCustomError(factory,'Unauthorized');await factory.connect(c.seller).create(terms);await expect(factory.connect(c.seller).create(terms)).revertedWithCustomError(factory,'DuplicateOffer');await expect(factory.connect(c.seller).create({...terms,token:await safe.getAddress()})).revertedWithCustomError(factory,'TokenNotApproved');});
});
