import { useEffect, useMemo, useState } from 'react'
import { useWallets } from '@privy-io/react-auth'
import { ArrowLeftIcon, BackspaceIcon, BanknotesIcon, ChartBarIcon, ChevronRightIcon, CurrencyDollarIcon, ShieldCheckIcon, SparklesIcon, XMarkIcon } from '@heroicons/react/24/outline'
import { createPublicClient, formatUnits, getAddress, http, isAddress } from 'viem'
import { Link } from '../lib/router'
import { upfrontXLayerChain } from '../lib/upfrontChains'

type CategoryId = 'stablecoin' | 'asset' | 'insurance'
type Asset = { symbol: string; name: string; aum: string; apy: number; color: string }
type FundingStatus = 'not_applied' | 'pending' | 'approved' | 'restricted' | undefined
const USDC = getAddress('0xB6CEceAB302E2E4948951eE7843FC24E92933061')
const ERC20_ABI = [{ type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] }] as const
const stablecoins: Asset[] = [
  { symbol: 'JupUSD', name: 'Jupiter USD', aum: '0.29M', apy: 5.69, color: '#7C3AED' },
  { symbol: 'USDC', name: 'USD Coin', aum: '09.54M', apy: 14.31, color: '#2775CA' },
  { symbol: 'USDT', name: 'Tether', aum: '7.78M', apy: 4.04, color: '#26A17B' },
  { symbol: 'EURC', name: 'Euro Coin', aum: '.88M', apy: 3.07, color: '#2563EB' },
  { symbol: 'USDS', name: 'Sky Dollar', aum: '.99M', apy: 5.05, color: '#F59E0B' },
]
const categories = [
  { id: 'stablecoin' as const, title: 'Stablecoin Yields', detail: 'Stablecoins and dollar-denominated yields.', Icon: CurrencyDollarIcon },
  { id: 'asset' as const, title: 'Asset Yields', detail: 'Earn yield on your asset holdings.', Icon: ChartBarIcon },
  { id: 'insurance' as const, title: 'Insurance Backed', detail: 'Returns generated by reinsurance markets.', Icon: ShieldCheckIcon },
]
const keys = ['1','2','3','4','5','6','7','8','9','.','0','backspace'] as const
const money = (value: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value)

function TokenIcon({ asset, small = false }: { asset: Asset; small?: boolean }) {
  return <span style={{ backgroundColor: asset.color }} className={'flex shrink-0 items-center justify-center rounded-full font-black text-white ring-2 ring-black ' + (small ? 'h-7 w-7 text-[8px]' : 'mx-auto h-16 w-16 text-xs')}>{asset.symbol.slice(0, 2)}</span>
}
function useUsdcBalance() {
  const { wallets } = useWallets()
  const address = wallets.find(item => item.walletClientType === 'privy' || item.walletClientType === 'privy-v2')?.address ?? ''
  const [balance, setBalance] = useState(0)
  useEffect(() => {
    if (!isAddress(address)) { setBalance(0); return }
    let active = true
    const read = async () => {
      try {
        const client = createPublicClient({ chain: upfrontXLayerChain, transport: http() })
        const units = await client.readContract({ address: USDC, abi: ERC20_ABI, functionName: 'balanceOf', args: [getAddress(address)] })
        if (active) setBalance(Number(formatUnits(units, 6)))
      } catch { /* Preserve the last confirmed value during quiet refresh failures. */ }
    }
    void read()
    const timer = window.setInterval(() => void read(), 15_000)
    const visible = () => { if (document.visibilityState === 'visible') void read() }
    document.addEventListener('visibilitychange', visible)
    return () => { active = false; window.clearInterval(timer); document.removeEventListener('visibilitychange', visible) }
  }, [address])
  return balance
}

export default function StreamPayGrow({ fundingStatus }: { fundingStatus: FundingStatus }) {
  const available = useUsdcBalance()
  const [category, setCategory] = useState<CategoryId>()
  const [asset, setAsset] = useState<Asset>()
  const [deposit, setDeposit] = useState(false)
  const [amount, setAmount] = useState('')
  const [year, setYear] = useState(23)
  const [notice, setNotice] = useState('')
  const projection = useMemo(() => Array.from({ length: 12 }, (_, index) => {
    const years = Math.round(index / 11 * 23)
    return { years, value: 10_000 * Math.pow(1 + (asset?.apy ?? 14.31) / 100, years) }
  }), [asset])
  const chosen = projection[Math.round(year / 23 * 11)]
  const entered = Number(amount || '0')
  const valid = entered >= 1 && entered <= available
  const key = (value: typeof keys[number]) => {
    setNotice('')
    if (value === 'backspace') return setAmount(current => current.slice(0, -1))
    if (value === '.') return setAmount(current => current.includes('.') ? current : (current || '0') + '.')
    setAmount(current => {
      const next = current === '0' ? value : current + value
      const parts = next.split('.')
      return parts[0].length <= 9 && (parts[1]?.length ?? 0) <= 2 ? next : current
    })
  }

  if (asset) return <section className="min-h-[calc(100dvh-6rem)] w-full max-w-md bg-black pb-28 pt-3 text-white">
    <div className="mx-auto h-1.5 w-12 rounded-full bg-white/20" />
    <div className="mt-4 flex justify-between">
      <button onClick={() => setAsset(undefined)} aria-label="Back to yields" className="flex h-10 w-10 items-center justify-center rounded-full bg-[#171717]"><ArrowLeftIcon className="h-5 w-5" /></button>
      <button onClick={() => setAsset(undefined)} aria-label="Close asset" className="flex h-10 w-10 items-center justify-center rounded-full bg-[#171717]"><XMarkIcon className="h-5 w-5" /></button>
    </div>
    <TokenIcon asset={asset} /><h1 className="mt-4 text-center text-3xl font-extrabold">{asset.symbol}</h1>
    <p className="mx-auto mt-2 max-w-xs text-center text-sm leading-6 text-zinc-400">Earn yield on {asset.name} via Jupiter Lend.</p>
    <div className="mt-5 flex gap-2 overflow-x-auto pb-1 text-[10px] font-bold text-zinc-300">
      {['No Lockups','Rewards Daily','Learn About ' + asset.symbol + ' ↗'].map(label => <span key={label} className="shrink-0 rounded-full border border-[#262626] bg-[#141414] px-3 py-2">{label}</span>)}
    </div>
    <article className="mt-4 rounded-[24px] border border-[#262626] bg-[#121212] p-5">
      <p className="text-xs font-bold text-zinc-500">APY</p><p className="mt-2 text-4xl font-black text-emerald-400">+{asset.apy.toFixed(3)}%</p>
      <div className="mt-5 grid grid-cols-2 border-t border-[#262626] pt-4"><div><p className="text-[10px] text-zinc-500">Min. Deposit</p><p className="mt-1 text-sm font-bold"></p></div><div><p className="text-[10px] text-zinc-500">AUM</p><p className="mt-1 text-sm font-bold">{asset.aum}</p></div></div>
    </article>
    <article className="mt-4 rounded-[24px] border border-[#262626] bg-[#121212] p-5">
      <div className="flex justify-between gap-3"><div><p className="text-xs font-bold">If invested 0,000 today</p><p className="mt-1 text-[10px] text-zinc-500">Illustrative compound growth</p></div><div className="text-right"><p className="text-[10px] text-zinc-500">{new Date().getFullYear() + chosen.years}</p><p className="mt-1 text-sm font-black">{money(chosen.value)}</p><p className="text-[10px] font-bold text-emerald-400">+{((chosen.value / 10_000 - 1) * 100).toFixed(1)}%</p></div></div>
      <div className="mt-6 flex h-36 items-end gap-2">{projection.map(point => <button key={point.years} onClick={() => setYear(point.years)} aria-label={'Year ' + (new Date().getFullYear() + point.years)} className={'min-w-0 flex-1 rounded-t-md ' + (point === chosen ? 'bg-emerald-400' : 'bg-emerald-900/60')} style={{ height: 24 + point.value / projection[projection.length - 1].value * 112 }} />)}</div>
    </article>
    <div className="fixed inset-x-0 bottom-[74px] z-40 mx-auto max-w-md bg-gradient-to-t from-black via-black px-4 pb-4 pt-8"><button onClick={() => { setAmount(''); setNotice(''); setDeposit(true) }} className="min-h-14 w-full rounded-full bg-emerald-500 text-sm font-black text-black">Start</button></div>
    {deposit && <DepositSheet asset={asset} amount={amount} available={available} valid={valid} notice={notice} onKey={key} onPercent={part => setAmount((available * part).toFixed(2).replace(/\.00$/, ''))} onClose={() => setDeposit(false)} onDeposit={() => setNotice('Yield deposits will open after the reviewed X Layer vault integration is connected. No funds were moved.')} />}
  </section>

  return <section className="min-h-[calc(100dvh-6rem)] w-full max-w-md bg-black pb-28 pt-6 text-white">
    <div className="relative text-center">
      <Link to="/funding?view=funding" className="absolute right-0 top-0 rounded-full border border-[#262626] bg-[#141414] px-3 py-2 text-[10px] font-bold text-zinc-300">Funding</Link>
      <h1 className="text-sm font-bold">Grow Balance</h1><p className="mt-7 text-5xl font-black tracking-[-0.05em]">/bin/bash</p>
      <span className="mt-3 inline-flex rounded-full bg-emerald-500/15 px-3 py-1.5 text-[10px] font-black text-emerald-400">Start up to 14.31%</span>
    </div>
    <div className="mt-10 flex items-end justify-between"><h2 className="text-sm font-black">Explore Assets</h2><p className="text-[10px] text-zinc-500">Indicative rates</p></div>
    <div className="mt-3 space-y-3">{categories.map(item => <button key={item.id} onClick={() => setCategory(item.id)} className="flex min-h-[104px] w-full items-center gap-4 rounded-[22px] border border-[#262626] bg-[#121212] p-4 text-left">
      <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-400"><item.Icon className="h-6 w-6" /></span>
      <span className="min-w-0 flex-1"><span className="block text-sm font-black">{item.title}</span><span className="mt-1 block text-[11px] leading-5 text-zinc-500">{item.detail}</span></span>
      {item.id === 'stablecoin' && <span className="flex -space-x-2">{stablecoins.slice(0,3).map(token => <TokenIcon key={token.symbol} asset={token} small />)}</span>}
      <span className="rounded-full bg-white px-3 py-2 text-[10px] font-black text-black">View</span>
    </button>)}</div>
    <Link to="/funding?view=funding" className="mt-5 flex items-center gap-3 rounded-[22px] border border-[#262626] bg-[#121212] p-4">
      <span className="flex h-11 w-11 items-center justify-center rounded-full bg-white/5"><BanknotesIcon className="h-5 w-5 text-zinc-300" /></span>
      <span className="min-w-0 flex-1"><span className="block text-xs font-black">Funding opportunities</span><span className="mt-1 block text-[10px] text-zinc-500">{fundingStatus === 'approved' ? 'Review verified work on X Layer.' : fundingStatus === 'pending' ? 'Application under review.' : 'Apply to become a funding partner.'}</span></span><ChevronRightIcon className="h-4 w-4 text-zinc-600" />
    </Link>
    {category && <CategorySheet category={category} onClose={() => setCategory(undefined)} onSelect={selected => { setCategory(undefined); setAsset(selected); setYear(23) }} />}
  </section>
}

function CategorySheet({ category, onClose, onSelect }: { category: CategoryId; onClose: () => void; onSelect: (asset: Asset) => void }) {
  const details = categories.find(item => item.id === category)!
  return <div className="fixed inset-0 z-[120] flex items-end bg-black/70 backdrop-blur-sm" onClick={onClose}><section onClick={event => event.stopPropagation()} className="mx-auto max-h-[82dvh] w-full max-w-md overflow-y-auto rounded-t-[28px] border border-[#262626] bg-[#111] px-5 pb-8 pt-3 text-white">
    <div className="mx-auto h-1.5 w-12 rounded-full bg-white/20" /><div className="mt-5 flex gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-400"><details.Icon className="h-6 w-6" /></span><div><h2 className="text-xl font-black">{details.title}</h2><p className="mt-1 text-xs leading-5 text-zinc-500">{details.detail}</p></div></div>
    {category === 'stablecoin' ? <div className="mt-6 divide-y divide-[#262626]">{stablecoins.map(item => <button key={item.symbol} onClick={() => onSelect(item)} className="flex w-full items-center gap-3 py-4 text-left"><TokenIcon asset={item} small /><span className="flex-1"><span className="block text-sm font-black">{item.symbol}</span><span className="mt-1 block text-[10px] text-zinc-500">AUM {item.aum}</span></span><span className="text-sm font-black text-emerald-400">+{item.apy.toFixed(2)}%</span><ChevronRightIcon className="h-4 w-4 text-zinc-600" /></button>)}</div> : <div className="mt-8 rounded-2xl border border-[#262626] bg-[#161616] px-4 py-8 text-center"><SparklesIcon className="mx-auto h-6 w-6 text-zinc-600" /><p className="mt-3 text-xs font-bold">Products are being reviewed</p><p className="mt-1 text-[10px] leading-5 text-zinc-500">Only reviewed USDC opportunities will be enabled.</p></div>}
  </section></div>
}

function DepositSheet({ asset, amount, available, valid, notice, onKey, onPercent, onClose, onDeposit }: { asset: Asset; amount: string; available: number; valid: boolean; notice: string; onKey: (key: typeof keys[number]) => void; onPercent: (part: number) => void; onClose: () => void; onDeposit: () => void }) {
  return <div className="fixed inset-0 z-[140] flex items-end bg-black/75 backdrop-blur-sm" onClick={onClose}><section onClick={event => event.stopPropagation()} className="mx-auto w-full max-w-md rounded-t-[28px] border border-[#262626] bg-[#111] px-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-3 text-white">
    <div className="mx-auto h-1.5 w-12 rounded-full bg-white/20" /><div className="mt-5 flex items-center justify-between"><h2 className="text-lg font-black">Deposit into {asset.symbol}</h2><span className="flex items-center gap-2 rounded-full border border-[#262626] bg-[#171717] px-3 py-2 text-xs font-bold"><TokenIcon asset={asset} small />{asset.symbol}⌄</span></div>
    <p className="mt-9 text-center text-5xl font-black tracking-[-0.05em]">{'$'}{amount || '0'}</p><p className="mt-2 text-center text-[10px] text-zinc-500">Available {available.toFixed(6)} USDC</p>
    {!valid && <div className="mt-6 rounded-2xl border border-[#262626] bg-[#181818] px-4 py-3 text-[11px] leading-5 text-zinc-400"><span className="font-bold text-white">No eligible assets</span> — Deposit more than  of any supported asset to start earning.</div>}
    {notice && <div role="status" className="mt-4 rounded-2xl bg-amber-400/10 px-4 py-3 text-[11px] leading-5 text-amber-200">{notice}</div>}
    <div className="mt-4 grid grid-cols-4 gap-2">{[.25,.5,.75,1].map((part,index) => <button key={part} onClick={() => onPercent(part)} className="rounded-full border border-[#262626] bg-[#171717] py-2.5 text-[10px] font-black">{index === 3 ? 'MAX' : Math.round(part * 100) + '%'}</button>)}</div>
    <div className="mt-4 grid grid-cols-3 gap-1">{keys.map(value => <button key={value} onClick={() => onKey(value)} className="flex min-h-12 items-center justify-center rounded-2xl text-xl font-bold active:bg-white/10">{value === 'backspace' ? <BackspaceIcon className="h-6 w-6" /> : value}</button>)}</div>
    <button disabled={!valid} onClick={onDeposit} className="mt-3 min-h-14 w-full rounded-full bg-emerald-500 text-sm font-black text-black disabled:bg-[#262626] disabled:text-zinc-600">Deposit</button><p className="mt-3 text-center text-[9px] text-zinc-600">Rates are variable. No yield is guaranteed.</p>
  </section></div>
}

