type Active = 'home' | 'agreements' | 'requests' | 'account'
function Bone({ className }: { className: string }) { return <span aria-hidden="true" className={`block animate-pulse rounded-lg bg-gray-200/85 [animation-duration:700ms] motion-reduce:animate-none dark:bg-white/[0.08] ${className}`} /> }

export function StreamPayLoadingState({ active }: { active: Active }) {
  if (active === 'home') return <section aria-busy="true" aria-label="Opening Home" className="w-full max-w-md space-y-4 py-5">
    <div className="rounded-[26px] bg-gray-950 p-5 dark:bg-white"><div className="flex justify-between"><Bone className="h-3 w-24 bg-white/20 dark:bg-gray-950/10" /><Bone className="h-9 w-9 rounded-full bg-white/15 dark:bg-gray-950/10" /></div><Bone className="mt-4 h-10 w-40 bg-white/20 dark:bg-gray-950/10" /></div>
    <div className="grid grid-cols-4 gap-2">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="rounded-2xl bg-white p-3 dark:bg-white/[0.035]"><Bone className="mx-auto h-6 w-6 rounded-full" /><Bone className="mx-auto mt-3 h-2.5 w-10" /></div>)}</div>
    <div className="rounded-[24px] bg-white p-4 dark:bg-white/[0.035]"><Bone className="h-3 w-24" />{Array.from({ length: 3 }).map((_, index) => <div key={index} className="mt-4 flex items-center gap-3"><Bone className="h-9 w-9 rounded-full" /><div className="flex-1"><Bone className="h-3 w-28" /><Bone className="mt-2 h-2.5 w-20" /></div><Bone className="h-3 w-12" /></div>)}</div>
  </section>
  if (active === 'account') return <section aria-busy="true" aria-label="Opening Account" className="w-full max-w-md py-7"><Bone className="mx-auto h-20 w-20 rounded-full" /><Bone className="mx-auto mt-4 h-5 w-32" /><Bone className="mx-auto mt-3 h-3 w-44" /><div className="mt-8 space-y-3">{Array.from({ length: 5 }).map((_, index) => <Bone key={index} className="h-16 w-full rounded-[22px]" />)}</div></section>
  return <section aria-busy="true" aria-label={active === 'requests' ? 'Opening Requests' : 'Opening Agreements'} className="w-full max-w-md py-5"><div className="grid grid-cols-2 gap-1 rounded-full bg-gray-200/70 p-1 dark:bg-white/[0.06]"><Bone className="h-10 rounded-full" /><Bone className="h-10 rounded-full" /></div><div className="mt-4 space-y-3">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="rounded-[24px] bg-white p-4 dark:bg-white/[0.035]"><div className="flex gap-3"><Bone className="h-10 w-10 rounded-2xl" /><div className="flex-1"><Bone className="h-3 w-20" /><Bone className="mt-3 h-4 w-3/4" /><Bone className="mt-2 h-3 w-full" /></div></div><Bone className="mt-4 h-11 w-full rounded-full" /></div>)}</div></section>
}
